/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface DScoreInterface extends ethers.utils.Interface {
  functions: {
    "calculateVotingPower(address)": FunctionFragment;
    "checkStaked(address)": FunctionFragment;
    "dc()": FunctionFragment;
    "decreaseDScore(address,uint256,uint256)": FunctionFragment;
    "ds()": FunctionFragment;
    "getDscore(address)": FunctionFragment;
    "increaseDScore(address,uint256,uint256)": FunctionFragment;
    "members(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setDC(address)": FunctionFragment;
    "stakeMembership(uint256)": FunctionFragment;
    "stakedCounter()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "calculateVotingPower",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "checkStaked", values: [string]): string;
  encodeFunctionData(functionFragment: "dc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "decreaseDScore",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "ds", values?: undefined): string;
  encodeFunctionData(functionFragment: "getDscore", values: [string]): string;
  encodeFunctionData(
    functionFragment: "increaseDScore",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "members", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "setDC", values: [string]): string;
  encodeFunctionData(
    functionFragment: "stakeMembership",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakedCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateVotingPower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkStaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "decreaseDScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getDscore", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "increaseDScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "members", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setDC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakeMembership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakedCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "DScoreDecreased(address,uint256,uint256)": EventFragment;
    "DScoreIncreased(address,uint256,uint256)": EventFragment;
    "Memberfrozen(address,uint256)": EventFragment;
    "MembershipStaked(address,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DScoreDecreased"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DScoreIncreased"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Memberfrozen"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MembershipStaked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export class DScore extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: DScoreInterface;

  functions: {
    calculateVotingPower(
      _member: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    checkStaked(_member: string, overrides?: CallOverrides): Promise<[boolean]>;

    dc(overrides?: CallOverrides): Promise<[string]>;

    decreaseDScore(
      _member: string,
      _factor: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    ds(overrides?: CallOverrides): Promise<[string]>;

    getDscore(
      _member: string,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        level: BigNumber;
        jobs: BigNumber;
        votes: BigNumber;
        reputation: BigNumber;
        staked: BigNumber;
        verified: BigNumber;
        audit: BigNumber;
      }
    >;

    increaseDScore(
      _member: string,
      _factor: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    members(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        level: BigNumber;
        jobs: BigNumber;
        votes: BigNumber;
        reputation: BigNumber;
        staked: BigNumber;
        verified: BigNumber;
        audit: BigNumber;
      }
    >;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setDC(
      _dCore: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    stakeMembership(
      _stakeAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    stakedCounter(overrides?: CallOverrides): Promise<[BigNumber]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  calculateVotingPower(
    _member: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  checkStaked(_member: string, overrides?: CallOverrides): Promise<boolean>;

  dc(overrides?: CallOverrides): Promise<string>;

  decreaseDScore(
    _member: string,
    _factor: BigNumberish,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  ds(overrides?: CallOverrides): Promise<string>;

  getDscore(
    _member: string,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      level: BigNumber;
      jobs: BigNumber;
      votes: BigNumber;
      reputation: BigNumber;
      staked: BigNumber;
      verified: BigNumber;
      audit: BigNumber;
    }
  >;

  increaseDScore(
    _member: string,
    _factor: BigNumberish,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  members(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      level: BigNumber;
      jobs: BigNumber;
      votes: BigNumber;
      reputation: BigNumber;
      staked: BigNumber;
      verified: BigNumber;
      audit: BigNumber;
    }
  >;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setDC(
    _dCore: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  stakeMembership(
    _stakeAmount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  stakedCounter(overrides?: CallOverrides): Promise<BigNumber>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    calculateVotingPower(
      _member: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkStaked(_member: string, overrides?: CallOverrides): Promise<boolean>;

    dc(overrides?: CallOverrides): Promise<string>;

    decreaseDScore(
      _member: string,
      _factor: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    ds(overrides?: CallOverrides): Promise<string>;

    getDscore(
      _member: string,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        level: BigNumber;
        jobs: BigNumber;
        votes: BigNumber;
        reputation: BigNumber;
        staked: BigNumber;
        verified: BigNumber;
        audit: BigNumber;
      }
    >;

    increaseDScore(
      _member: string,
      _factor: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    members(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        level: BigNumber;
        jobs: BigNumber;
        votes: BigNumber;
        reputation: BigNumber;
        staked: BigNumber;
        verified: BigNumber;
        audit: BigNumber;
      }
    >;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setDC(_dCore: string, overrides?: CallOverrides): Promise<void>;

    stakeMembership(
      _stakeAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    stakedCounter(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    DScoreDecreased(
      member?: null,
      factor?: null,
      amountDecreased?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { member: string; factor: BigNumber; amountDecreased: BigNumber }
    >;

    DScoreIncreased(
      member?: null,
      factor?: null,
      amountIncreased?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { member: string; factor: BigNumber; amountIncreased: BigNumber }
    >;

    Memberfrozen(
      member?: null,
      timeFrozen?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { member: string; timeFrozen: BigNumber }
    >;

    MembershipStaked(
      member?: null,
      amountStaked?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { member: string; amountStaked: BigNumber }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;
  };

  estimateGas: {
    calculateVotingPower(
      _member: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkStaked(_member: string, overrides?: CallOverrides): Promise<BigNumber>;

    dc(overrides?: CallOverrides): Promise<BigNumber>;

    decreaseDScore(
      _member: string,
      _factor: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    ds(overrides?: CallOverrides): Promise<BigNumber>;

    getDscore(_member: string, overrides?: CallOverrides): Promise<BigNumber>;

    increaseDScore(
      _member: string,
      _factor: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    members(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setDC(
      _dCore: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    stakeMembership(
      _stakeAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    stakedCounter(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    calculateVotingPower(
      _member: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkStaked(
      _member: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    dc(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    decreaseDScore(
      _member: string,
      _factor: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    ds(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getDscore(
      _member: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    increaseDScore(
      _member: string,
      _factor: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    members(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setDC(
      _dCore: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    stakeMembership(
      _stakeAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    stakedCounter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
